//! Strongly-typed AST types for Go, auto-generated from
//! [`tree-sitter-go`](https://docs.rs/tree-sitter-go)'s `node-types.json`.
//!
//! This crate is generated by [`treesitter-types`](https://docs.rs/treesitter-types) and is
//! automatically kept up to date when a new version of the grammar crate is released.
//!
//! These types have been tested by parsing the
//! [Go compiler](https://github.com/golang/go) source code.
//!
//! See the [Tree-sitter](https://tree-sitter.github.io/tree-sitter/) project for more
//! information about the underlying parser framework.
//!
//! # Example
//!
//! ```
//! use treesitter_types_go::*;
//!
//! let src = b"\
//! package main
//!
//! import \"fmt\"
//!
//! func main() {
//!     fmt.Println(\"Hello, World!\")
//! }
//! ";
//!
//! let mut parser = tree_sitter::Parser::new();
//! parser.set_language(&tree_sitter_go::LANGUAGE.into()).unwrap();
//! let tree = parser.parse(src, None).unwrap();
//!
//! let source_file = SourceFile::from_node(tree.root_node(), src).unwrap();
//!
//! // The source file has three top-level children:
//! // a package clause, an import declaration, and a function declaration.
//! assert_eq!(source_file.children.len(), 3);
//! ```

pub use treesitter_types::{FromNode, LeafNode, ParseError, Span, Spanned};

mod generated;
pub use generated::*;
