//! Strongly-typed AST types for Rust, auto-generated from
//! [`tree-sitter-rust`](https://docs.rs/tree-sitter-rust)'s `node-types.json`.
//!
//! This crate is generated by [`treesitter-types`](https://docs.rs/treesitter-types) and is
//! automatically kept up to date when a new version of the grammar crate is released.
//!
//! These types have been tested by parsing the
//! [Rust compiler](https://github.com/rust-lang/rust) source code.
//!
//! See the [Tree-sitter](https://tree-sitter.github.io/tree-sitter/) project for more
//! information about the underlying parser framework.
//!
//! # Example
//!
//! ```
//! use treesitter_types_rust::*;
//!
//! let src = b"\
//! fn main() {
//!     println!(\"Hello, World!\");
//! }
//! ";
//!
//! let mut parser = tree_sitter::Parser::new();
//! parser.set_language(&tree_sitter_rust::LANGUAGE.into()).unwrap();
//! let tree = parser.parse(src, None).unwrap();
//!
//! let source_file = SourceFile::from_node(tree.root_node(), src).unwrap();
//!
//! // The source file has one top-level child: the `main` function definition.
//! assert_eq!(source_file.children.len(), 1);
//!
//! // Extract the function item and inspect its fields.
//! let SourceFileChildren::DeclarationStatement(decl) = &source_file.children[0] else {
//!     panic!("expected a declaration statement");
//! };
//! let DeclarationStatement::FunctionItem(func) = decl.as_ref() else {
//!     panic!("expected a function item");
//! };
//! let FunctionItemName::Identifier(name) = &func.name else {
//!     panic!("expected an identifier");
//! };
//! assert_eq!(name.text(), "main");
//! assert!(func.return_type.is_none());
//! ```

pub use treesitter_types::{FromNode, LeafNode, ParseError, Span, Spanned};

mod generated;
pub use generated::*;
