//! Strongly-typed AST types for Markdown, auto-generated from
//! [`tree-sitter-md`](https://docs.rs/tree-sitter-md)'s `node-types.json`.
//!
//! This crate is generated by [`treesitter-types`](https://docs.rs/treesitter-types) and is
//! automatically kept up to date when a new version of the grammar crate is released.
//!
//! See the [Tree-sitter](https://tree-sitter.github.io/tree-sitter/) project for more
//! information about the underlying parser framework.
//!
//! # Example
//!
//! ```
//! use treesitter_types_markdown::*;
//!
//! let src = b"\
//! # Hello, World!
//!
//! This is a paragraph.
//! ";
//!
//! let mut parser = tree_sitter::Parser::new();
//! parser.set_language(&tree_sitter_md::LANGUAGE.into()).unwrap();
//! let tree = parser.parse(src, None).unwrap();
//!
//! let document = Document::from_node(tree.root_node(), src).unwrap();
//!
//! // The document has one top-level child: a section containing the heading
//! // and paragraph.
//! assert_eq!(document.children.len(), 1);
//! let DocumentChildren::Section(section) = &document.children[0] else {
//!     panic!("expected a section");
//! };
//! assert_eq!(section.span.start.row, 0);
//! ```

pub use treesitter_types::{FromNode, LeafNode, ParseError, Span, Spanned};

mod generated;
pub use generated::*;
