//! Strongly-typed AST types for PHP, auto-generated from
//! [`tree-sitter-php`](https://docs.rs/tree-sitter-php)'s `node-types.json`.
//!
//! This crate is generated by [`treesitter-types`](https://docs.rs/treesitter-types) and is
//! automatically kept up to date when a new version of the grammar crate is released.
//!
//! These types have been tested by parsing the
//! [Laravel](https://github.com/laravel/framework) source code.
//!
//! See the [Tree-sitter](https://tree-sitter.github.io/tree-sitter/) project for more
//! information about the underlying parser framework.
//!
//! # Example
//!
//! ```
//! use treesitter_types_php::*;
//!
//! let src = b"\
//! <?php
//!
//! function greet($name) {
//!     echo \"Hello, $name!\";
//! }
//!
//! greet(\"World\");
//! ";
//!
//! let mut parser = tree_sitter::Parser::new();
//! parser.set_language(&tree_sitter_php::LANGUAGE_PHP.into()).unwrap();
//! let tree = parser.parse(src, None).unwrap();
//!
//! let program = Program::from_node(tree.root_node(), src).unwrap();
//! assert!(!program.children.is_empty());
//! ```

pub use treesitter_types::{FromNode, LeafNode, ParseError, Span, Spanned};

mod generated;
pub use generated::*;
