//! Strongly-typed AST types for PHP, auto-generated from
//! [`tree-sitter-php`](https://docs.rs/tree-sitter-php)'s `node-types.json`.
//!
//! This crate is generated by [`treesitter-types`](https://docs.rs/treesitter-types) and is
//! automatically kept up to date when a new version of the grammar crate is released.
//!
//! These types have been tested by parsing the
//! [Laravel](https://github.com/laravel/framework) source code.
//!
//! See the [Tree-sitter](https://tree-sitter.github.io/tree-sitter/) project for more
//! information about the underlying parser framework.
//!
//! # Example
//!
//! ```
//! use treesitter_types_php::*;
//!
//! // A minimal PHP hello-world program.
//! let src = b"\
//! <?php
//!
//! function greet($name) {
//!     echo \"Hello, $name!\";
//! }
//!
//! greet(\"World\");
//! ";
//!
//! // Parse the source with tree-sitter and convert into typed AST.
//! let mut parser = tree_sitter::Parser::new();
//! parser.set_language(&tree_sitter_php::LANGUAGE_PHP.into()).unwrap();
//! let tree = parser.parse(src, None).unwrap();
//! let program = Program::from_node(tree.root_node(), src).unwrap();
//!
//! // First child is the `<?php` tag, then our statements.
//! assert!(program.children.len() >= 3);
//!
//! // The function definition — `function greet($name) { ... }`.
//! let ProgramChildren::Statement(stmt) = &program.children[1] else {
//!     panic!("expected a statement");
//! };
//! let Statement::FunctionDefinition(func) = stmt.as_ref() else {
//!     panic!("expected a function definition");
//! };
//! assert_eq!(func.name.text(), "greet");
//! assert_eq!(func.parameters.children.len(), 1); // one parameter: `$name`
//! assert!(func.return_type.is_none());            // no return type declaration
//! ```

pub use treesitter_types::{FromNode, LeafNode, ParseError, Span, Spanned};

mod generated;
pub use generated::*;
