//! Strongly-typed AST types for JSON, auto-generated from
//! [`tree-sitter-json`](https://docs.rs/tree-sitter-json)'s `node-types.json`.
//!
//! This crate is generated by [`treesitter-types`](https://docs.rs/treesitter-types) and is
//! automatically kept up to date when a new version of the grammar crate is released.
//!
//! These types have been tested by parsing the
//! [SchemaStore](https://github.com/SchemaStore/schemastore) source code.
//!
//! See the [Tree-sitter](https://tree-sitter.github.io/tree-sitter/) project for more
//! information about the underlying parser framework.
//!
//! # Example
//!
//! ```
//! use treesitter_types_json::*;
//!
//! let src = b"\
//! {
//!     \"hello\": \"world\",
//!     \"count\": 42
//! }
//! ";
//!
//! let mut parser = tree_sitter::Parser::new();
//! parser.set_language(&tree_sitter_json::LANGUAGE.into()).unwrap();
//! let tree = parser.parse(src, None).unwrap();
//!
//! let document = Document::from_node(tree.root_node(), src).unwrap();
//!
//! // The document has one top-level child: the root JSON object.
//! assert_eq!(document.children.len(), 1);
//! ```

pub use treesitter_types::{FromNode, LeafNode, ParseError, Span, Spanned};

mod generated;
pub use generated::*;
