//! Strongly-typed AST types for Python, auto-generated from
//! [`tree-sitter-python`](https://docs.rs/tree-sitter-python)'s `node-types.json`.
//!
//! This crate is generated by [`treesitter-types`](https://docs.rs/treesitter-types) and is
//! automatically kept up to date when a new version of the grammar crate is released.
//!
//! These types have been tested by parsing the
//! [CPython](https://github.com/python/cpython) source code.
//!
//! See the [Tree-sitter](https://tree-sitter.github.io/tree-sitter/) project for more
//! information about the underlying parser framework.
//!
//! # Example
//!
//! ```
//! use treesitter_types_python::*;
//!
//! let src = b"\
//! def main():
//!     print(\"Hello, World!\")
//!
//! main()
//! ";
//!
//! let mut parser = tree_sitter::Parser::new();
//! parser.set_language(&tree_sitter_python::LANGUAGE.into()).unwrap();
//! let tree = parser.parse(src, None).unwrap();
//!
//! let module = Module::from_node(tree.root_node(), src).unwrap();
//!
//! // The module has two top-level children:
//! // a function definition and a function call expression.
//! assert_eq!(module.children.len(), 2);
//!
//! // Extract the function definition and inspect its fields.
//! let ModuleChildren::CompoundStatement(stmt) = &module.children[0] else {
//!     panic!("expected a compound statement");
//! };
//! let CompoundStatement::FunctionDefinition(func) = stmt.as_ref() else {
//!     panic!("expected a function definition");
//! };
//! assert_eq!(func.name.text(), "main");
//! assert!(func.return_type.is_none());
//! ```

pub use treesitter_types::{FromNode, LeafNode, ParseError, Span, Spanned};

mod generated;
pub use generated::*;
