//! Strongly-typed AST types for YAML, auto-generated from
//! [`tree-sitter-yaml`](https://docs.rs/tree-sitter-yaml)'s `node-types.json`.
//!
//! This crate is generated by [`treesitter-types`](https://docs.rs/treesitter-types) and is
//! automatically kept up to date when a new version of the grammar crate is released.
//!
//! See the [Tree-sitter](https://tree-sitter.github.io/tree-sitter/) project for more
//! information about the underlying parser framework.
//!
//! # Example
//!
//! ```
//! use treesitter_types_yaml::*;
//!
//! let src = b"\
//! name: hello
//! version: 1.0.0
//! dependencies:
//!   - foo
//!   - bar
//! ";
//!
//! let mut parser = tree_sitter::Parser::new();
//! parser.set_language(&tree_sitter_yaml::LANGUAGE.into()).unwrap();
//! let tree = parser.parse(src, None).unwrap();
//!
//! let stream = Stream::from_node(tree.root_node(), src).unwrap();
//! assert!(!stream.children.is_empty());
//! ```

pub use treesitter_types::{FromNode, LeafNode, ParseError, Span, Spanned};

mod generated;
pub use generated::*;
