//! Strongly-typed AST types for regular expressions, auto-generated from
//! [`tree-sitter-regex`](https://docs.rs/tree-sitter-regex)'s `node-types.json`.
//!
//! This crate is generated by [`treesitter-types`](https://docs.rs/treesitter-types) and is
//! automatically kept up to date when a new version of the grammar crate is released.
//!
//! See the [Tree-sitter](https://tree-sitter.github.io/tree-sitter/) project for more
//! information about the underlying parser framework.
//!
//! # Example
//!
//! ```
//! use treesitter_types_regex::*;
//!
//! // A regular expression with a character class and a capture group.
//! let src = b"[a-z]+([0-9]*)";
//!
//! // Parse the regex with tree-sitter and convert into typed AST.
//! let mut parser = tree_sitter::Parser::new();
//! parser.set_language(&tree_sitter_regex::LANGUAGE.into()).unwrap();
//! let tree = parser.parse(src, None).unwrap();
//! let pattern = Pattern::from_node(tree.root_node(), src).unwrap();
//!
//! // The pattern spans the entire input.
//! assert_eq!(pattern.span.start.column, 0);
//! assert_eq!(pattern.span.end.column, 14);
//! ```

pub use treesitter_types::{FromNode, LeafNode, ParseError, Span, Spanned};
pub use treesitter_types::tree_sitter;
pub use tree_sitter_regex;

mod generated;
pub use generated::*;
