//! Strongly-typed AST types for Java, auto-generated from
//! [`tree-sitter-java`](https://docs.rs/tree-sitter-java)'s `node-types.json`.
//!
//! This crate is generated by [`treesitter-types`](https://docs.rs/treesitter-types) and is
//! automatically kept up to date when a new version of the grammar crate is released.
//!
//! These types have been tested by parsing the
//! [Spring Framework](https://github.com/spring-projects/spring-framework) source code.
//!
//! See the [Tree-sitter](https://tree-sitter.github.io/tree-sitter/) project for more
//! information about the underlying parser framework.
//!
//! # Example
//!
//! ```
//! use treesitter_types_java::*;
//!
//! let src = b"\
//! class Hello {
//!     public static void main(String[] args) {
//!         System.out.println(\"Hello, World!\");
//!     }
//! }
//! ";
//!
//! let mut parser = tree_sitter::Parser::new();
//! parser.set_language(&tree_sitter_java::LANGUAGE.into()).unwrap();
//! let tree = parser.parse(src, None).unwrap();
//!
//! let program = Program::from_node(tree.root_node(), src).unwrap();
//!
//! // The program has one top-level child: the `Hello` class declaration.
//! assert_eq!(program.children.len(), 1);
//! ```

pub use treesitter_types::{FromNode, LeafNode, ParseError, Span, Spanned};

mod generated;
pub use generated::*;
