//! Strongly-typed AST types for Scala, auto-generated from
//! [`tree-sitter-scala`](https://docs.rs/tree-sitter-scala)'s `node-types.json`.
//!
//! This crate is generated by [`treesitter-types`](https://docs.rs/treesitter-types) and is
//! automatically kept up to date when a new version of the grammar crate is released.
//!
//! These types have been tested by parsing the
//! [Apache Spark](https://github.com/apache/spark) source code.
//!
//! See the [Tree-sitter](https://tree-sitter.github.io/tree-sitter/) project for more
//! information about the underlying parser framework.
//!
//! # Example
//!
//! ```
//! use treesitter_types_scala::*;
//!
//! // A minimal Scala hello-world program.
//! let src = b"\
//! object Hello {
//!   def main(args: Array[String]): Unit = {
//!     println(\"Hello, World!\")
//!   }
//! }
//! ";
//!
//! // Parse the source with tree-sitter and convert into typed AST.
//! let mut parser = tree_sitter::Parser::new();
//! parser.set_language(&tree_sitter_scala::LANGUAGE.into()).unwrap();
//! let tree = parser.parse(src, None).unwrap();
//! let cu = CompilationUnit::from_node(tree.root_node(), src).unwrap();
//!
//! // The compilation unit has one top-level child: the `Hello` object.
//! assert_eq!(cu.children.len(), 1);
//!
//! let CompilationUnitChildren::Definition(def) = &cu.children[0] else {
//!     panic!("expected a definition");
//! };
//! let Definition::ObjectDefinition(obj) = def.as_ref() else {
//!     panic!("expected an object definition");
//! };
//! let ObjectDefinitionName::Identifier(name) = &obj.name else {
//!     panic!("expected an identifier");
//! };
//! assert_eq!(name.text(), "Hello");
//! assert!(obj.extend.is_none()); // no `extends` clause
//!
//! // The object body contains one method definition.
//! assert_eq!(obj.body.len(), 1);
//! ```

pub use treesitter_types::{FromNode, LeafNode, ParseError, Span, Spanned};

mod generated;
pub use generated::*;
