//! Strongly-typed AST types for C, auto-generated from
//! [`tree-sitter-c`](https://docs.rs/tree-sitter-c)'s `node-types.json`.
//!
//! This crate is generated by [`treesitter-types`](https://docs.rs/treesitter-types) and is
//! automatically kept up to date when a new version of the grammar crate is released.
//!
//! These types have been tested by parsing the
//! [Git](https://github.com/git/git) source code.
//!
//! See the [Tree-sitter](https://tree-sitter.github.io/tree-sitter/) project for more
//! information about the underlying parser framework.
//!
//! # Example
//!
//! ```
//! use treesitter_types_c::*;
//!
//! let src = b"\
//! #include <stdio.h>
//!
//! int main() {
//!     printf(\"Hello, World!\\n\");
//!     return 0;
//! }
//! ";
//!
//! let mut parser = tree_sitter::Parser::new();
//! parser.set_language(&tree_sitter_c::LANGUAGE.into()).unwrap();
//! let tree = parser.parse(src, None).unwrap();
//!
//! let translation_unit = TranslationUnit::from_node(tree.root_node(), src).unwrap();
//!
//! // The translation unit has two top-level children:
//! // a #include directive and the `main` function definition.
//! assert_eq!(translation_unit.children.len(), 2);
//! ```

pub use treesitter_types::{FromNode, LeafNode, ParseError, Span, Spanned};

mod generated;
pub use generated::*;
