//! Strongly-typed AST types for TOML, auto-generated from
//! [`tree-sitter-toml-ng`](https://docs.rs/tree-sitter-toml-ng)'s `node-types.json`.
//!
//! This crate is generated by [`treesitter-types`](https://docs.rs/treesitter-types) and is
//! automatically kept up to date when a new version of the grammar crate is released.
//!
//! See the [Tree-sitter](https://tree-sitter.github.io/tree-sitter/) project for more
//! information about the underlying parser framework.
//!
//! # Example
//!
//! ```
//! use treesitter_types_toml::*;
//!
//! // A small TOML document.
//! let src = b"\
//! [package]
//! name = \"hello\"
//! version = \"1.0.0\"
//! ";
//!
//! // Parse the source with tree-sitter and convert into typed AST.
//! let mut parser = tree_sitter::Parser::new();
//! parser.set_language(&tree_sitter_toml_ng::LANGUAGE.into()).unwrap();
//! let tree = parser.parse(src, None).unwrap();
//! let document = Document::from_node(tree.root_node(), src).unwrap();
//!
//! // The document has one top-level child: a [package] table.
//! assert_eq!(document.children.len(), 1);
//!
//! let DocumentChildren::Table(table) = &document.children[0] else {
//!     panic!("expected a table");
//! };
//! // The table contains the key-value pairs: `name` and `version`.
//! assert!(!table.children.is_empty());
//! assert_eq!(table.span.start.row, 0);
//! ```

pub use treesitter_types::{FromNode, LeafNode, ParseError, Span, Spanned};
pub use tree_sitter;
pub use tree_sitter_toml_ng;

mod generated;
pub use generated::*;
