//! Strongly-typed AST types for C#, auto-generated from
//! [`tree-sitter-c-sharp`](https://docs.rs/tree-sitter-c-sharp)'s `node-types.json`.
//!
//! This crate is generated by [`treesitter-types`](https://docs.rs/treesitter-types) and is
//! automatically kept up to date when a new version of the grammar crate is released.
//!
//! These types have been tested by parsing the
//! [.NET Runtime](https://github.com/dotnet/runtime) source code.
//!
//! See the [Tree-sitter](https://tree-sitter.github.io/tree-sitter/) project for more
//! information about the underlying parser framework.
//!
//! # Example
//!
//! ```
//! use treesitter_types_c_sharp::*;
//!
//! let src = b"\
//! using System;
//!
//! class Hello {
//!     static void Main() {
//!         Console.WriteLine(\"Hello, World!\");
//!     }
//! }
//! ";
//!
//! let mut parser = tree_sitter::Parser::new();
//! parser.set_language(&tree_sitter_c_sharp::LANGUAGE.into()).unwrap();
//! let tree = parser.parse(src, None).unwrap();
//!
//! let cu = CompilationUnit::from_node(tree.root_node(), src).unwrap();
//! assert_eq!(cu.children.len(), 2);
//!
//! // Extract the class declaration and inspect its name.
//! let CompilationUnitChildren::TypeDeclaration(type_decl) = &cu.children[1] else {
//!     panic!("expected a type declaration");
//! };
//! let TypeDeclaration::ClassDeclaration(class) = type_decl.as_ref() else {
//!     panic!("expected a class declaration");
//! };
//! assert_eq!(class.name.text(), "Hello");
//! ```

pub use treesitter_types::{FromNode, LeafNode, ParseError, Span, Spanned};

mod generated;
pub use generated::*;
