//! Strongly-typed AST types for TypeScript, auto-generated from
//! [`tree-sitter-typescript`](https://docs.rs/tree-sitter-typescript)'s `node-types.json`.
//!
//! This crate is generated by [`treesitter-types`](https://docs.rs/treesitter-types) and is
//! automatically kept up to date when a new version of the grammar crate is released.
//!
//! These types have been tested by parsing the
//! [TypeScript](https://github.com/microsoft/TypeScript) source code.
//!
//! See the [Tree-sitter](https://tree-sitter.github.io/tree-sitter/) project for more
//! information about the underlying parser framework.
//!
//! # Example
//!
//! ```
//! use treesitter_types_typescript::*;
//!
//! let src = b"\
//! function greet(name: string): void {
//!     console.log(\"Hello, \" + name + \"!\");
//! }
//!
//! greet(\"World\");
//! ";
//!
//! let mut parser = tree_sitter::Parser::new();
//! parser
//!     .set_language(&tree_sitter_typescript::LANGUAGE_TYPESCRIPT.into())
//!     .unwrap();
//! let tree = parser.parse(src, None).unwrap();
//!
//! let program = Program::from_node(tree.root_node(), src).unwrap();
//! assert_eq!(program.children.len(), 2);
//!
//! // Extract the function declaration and inspect its fields.
//! let ProgramChildren::Statement(stmt) = &program.children[0] else {
//!     panic!("expected a statement");
//! };
//! let Statement::Declaration(decl) = stmt.as_ref() else {
//!     panic!("expected a declaration");
//! };
//! let Declaration::FunctionDeclaration(func) = decl.as_ref() else {
//!     panic!("expected a function declaration");
//! };
//! assert_eq!(func.name.text(), "greet");
//! assert!(func.return_type.is_some());
//! ```

pub use treesitter_types::{FromNode, LeafNode, ParseError, Span, Spanned};

mod generated;
pub use generated::*;
