//! Strongly-typed AST types for CSS, auto-generated from
//! [`tree-sitter-css`](https://docs.rs/tree-sitter-css)'s `node-types.json`.
//!
//! This crate is generated by [`treesitter-types`](https://docs.rs/treesitter-types) and is
//! automatically kept up to date when a new version of the grammar crate is released.
//!
//! These types have been tested by parsing the
//! [Bootstrap](https://github.com/twbs/bootstrap) source code.
//!
//! See the [Tree-sitter](https://tree-sitter.github.io/tree-sitter/) project for more
//! information about the underlying parser framework.
//!
//! # Example
//!
//! ```
//! use treesitter_types_css::*;
//!
//! let src = b"\
//! body {
//!     color: red;
//!     font-size: 16px;
//! }
//! ";
//!
//! let mut parser = tree_sitter::Parser::new();
//! parser.set_language(&tree_sitter_css::LANGUAGE.into()).unwrap();
//! let tree = parser.parse(src, None).unwrap();
//!
//! let stylesheet = Stylesheet::from_node(tree.root_node(), src).unwrap();
//! assert_eq!(stylesheet.children.len(), 1);
//!
//! // Extract the rule set — it contains the selectors and declarations.
//! let StylesheetChildren::RuleSet(rule_set) = &stylesheet.children[0] else {
//!     panic!("expected a rule set");
//! };
//! assert!(!rule_set.children.is_empty());
//! ```

pub use treesitter_types::{FromNode, LeafNode, ParseError, Span, Spanned};

mod generated;
pub use generated::*;
