//! Strongly-typed AST types for JavaScript, auto-generated from
//! [`tree-sitter-javascript`](https://docs.rs/tree-sitter-javascript)'s `node-types.json`.
//!
//! This crate is generated by [`treesitter-types`](https://docs.rs/treesitter-types) and is
//! automatically kept up to date when a new version of the grammar crate is released.
//!
//! These types have been tested by parsing the
//! [Node.js](https://github.com/nodejs/node) source code.
//!
//! See the [Tree-sitter](https://tree-sitter.github.io/tree-sitter/) project for more
//! information about the underlying parser framework.
//!
//! # Example
//!
//! ```
//! use treesitter_types_javascript::*;
//!
//! let src = b"\
//! function greet(name) {
//!     console.log(\"Hello, \" + name + \"!\");
//! }
//!
//! greet(\"World\");
//! ";
//!
//! let mut parser = tree_sitter::Parser::new();
//! parser.set_language(&tree_sitter_javascript::LANGUAGE.into()).unwrap();
//! let tree = parser.parse(src, None).unwrap();
//!
//! let program = Program::from_node(tree.root_node(), src).unwrap();
//!
//! // The program has two top-level children:
//! // a function declaration and an expression statement.
//! assert_eq!(program.children.len(), 2);
//! ```

pub use treesitter_types::{FromNode, LeafNode, ParseError, Span, Spanned};

mod generated;
pub use generated::*;
